#!/usr/bin/env bash
set -euo pipefail

# Change to the directory where this script lives (the repo root).
cd "$(dirname "$0")"

VAULT_DIR="./beta-vault"
VAULT="$VAULT_DIR/vault"
TLS_DIR="$VAULT/tls"
EC_DIR="$TLS_DIR/ec"
MMDB_DIR="$VAULT_DIR/config/mmdb"
ARIN_DIR="$VAULT_DIR/config/arindb"
SECRETS_FILE="$VAULT_DIR/beta-secrets.env"

mkdir -p "$TLS_DIR" "$EC_DIR" "$MMDB_DIR" "$ARIN_DIR"

# Generate a 32-character random hex string.
rand32() {
    openssl rand -hex 16
}

# Generate 64 random bytes encoded as base64.
rand_b64_64() {
    openssl rand -base64 64 | tr -d '\n'
}

# Ensure the secrets env file and matching vault yml files exist.
# The env file is the single source of truth for passwords used by the
# Compose stack. It is kept out of git.
ensure_secrets() {
    if [ ! -f "$SECRETS_FILE" ]; then
        echo "Generating beta vault secrets..."
        POSTGRES_PASSWORD=$(rand32)
        REDIS_PASSWORD=$(rand32)
        JWT_SECRET=$(rand_b64_64)
        PASSWORD_PEPPER=$(rand32)
        CLIENT_IP_HASH_PEPPER=$(rand32)
        PROXY_SECRET=$(rand32)

        cat > "$SECRETS_FILE" <<EOF
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
JWT_SECRET=$JWT_SECRET
PASSWORD_PEPPER=$PASSWORD_PEPPER
CLIENT_IP_HASH_PEPPER=$CLIENT_IP_HASH_PEPPER
PROXY_SECRET=$PROXY_SECRET
EOF
        chmod 600 "$SECRETS_FILE"
    else
        echo "Using existing beta secrets from $SECRETS_FILE"
        # shellcheck disable=SC1090
        source "$SECRETS_FILE"
    fi

    # The Postgres and Redis services are configured via the env file too,
    # but the application still reads these values from yml files in the
    # mounted vault. Keep them in sync every run so a deleted/missing yml is
    # repaired without changing the passwords or invalidating data volumes.
    cat > "$VAULT/pg.yml" <<EOF
authority: "postgres:5432"
user: "postgres"
password: "${POSTGRES_PASSWORD}"
db: "postgres"
EOF

    cat > "$VAULT/redis.yml" <<EOF
authority: "redis:6379"
password: "${REDIS_PASSWORD}"
db: 0
cluster: false
EOF

    cat > "$VAULT/jwt.yml" <<EOF
# Generated by beta-setup.sh. tls_key_paths are vault-relative paths to PEM private keys.
secret: "${JWT_SECRET}"
issuer: "urnetwork-beta"
tls_key_paths:
  - "tls/jwt-rsa.pem"
  - "tls/ec/jwt-ec.pem"
EOF

    cat > "$VAULT/password.yml" <<EOF
pepper: "${PASSWORD_PEPPER}"
EOF

    cat > "$VAULT/client.yml" <<EOF
client_ip_hash_pepper: "${CLIENT_IP_HASH_PEPPER}"
EOF

    cat > "$VAULT/proxy.yml" <<EOF
# Generated by beta-setup.sh
secrets:
  - "${PROXY_SECRET}"
EOF
}

ensure_secrets

# Generate JWT keys if missing.
if [ ! -f "$TLS_DIR/jwt-rsa.pem" ]; then
    echo "Generating RSA JWT key..."
    openssl genrsa -out "$TLS_DIR/jwt-rsa.pem" 2048
    openssl rsa -in "$TLS_DIR/jwt-rsa.pem" -pubout -out "$TLS_DIR/jwt-rsa.pub.pem"
fi

if [ ! -f "$EC_DIR/jwt-ec.pem" ]; then
    echo "Generating EC JWT key..."
    openssl ecparam -genkey -name prime256v1 -out "$EC_DIR/jwt-ec.pem"
    openssl ec -in "$EC_DIR/jwt-ec.pem" -pubout -out "$EC_DIR/jwt-ec.pub.pem"
fi

# Download or generate MMDBs if missing.
if [ ! -f "$MMDB_DIR/ip-ipinfo.mmdb" ] || [ ! -f "$ARIN_DIR/arin.mmdb" ]; then
    echo "Generating beta MMDBs..."
    go run ./scripts/gen-beta-mmdb.go
else
    echo "Beta MMDBs already present."
fi

# Build and start the Docker Compose stack.
echo "Detecting public IP..."
PUBLIC_IP="${PUBLIC_IP:-$(curl -s icanhazip.com || curl -s ifconfig.me || echo "127.0.0.1")}"
export PUBLIC_IP
echo "Using PUBLIC_IP=$PUBLIC_IP"

echo "Building beta server image..."
# Stop only containers, never the named data volume. This keeps Postgres data
# across updates. To intentionally wipe the database, run `./beta-down.sh -v`.
docker compose -f docker-compose.beta.yml down 2>/dev/null || true
docker compose -f docker-compose.beta.yml build

echo "Starting Postgres and Redis..."
docker compose -f docker-compose.beta.yml up -d postgres redis

# Wait for health checks.
until docker compose -f docker-compose.beta.yml ps --format table 2>/dev/null | grep -E 'postgres.*healthy|redis.*healthy' >/dev/null; do
    sleep 1
done

echo "Running migrations..."
docker compose -f docker-compose.beta.yml run --rm migrate

echo "Starting API, Connect, and Taskworker services..."
docker compose -f docker-compose.beta.yml up -d api connect taskworker

echo
echo "Beta network running:"
echo "  API:     http://$PUBLIC_IP:8080"
echo "  Connect: ws://$PUBLIC_IP:5080/"
echo
echo "All generated secrets live in $SECRETS_FILE and beta-vault/vault/*.yml"
echo "These files are NOT tracked by git."
echo "Postgres data is preserved across ./beta-setup.sh runs in the named volume."
echo "To intentionally wipe the database, run ./beta-down.sh -v."
echo "To use from another machine, open TCP ports 8080, 5080, and 15080."
